version: "3"

services:
  db:
    image: postgres:15.6
    container_name: node-csv-practice
    ports:
      - 5440:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=passw0rd
volumes:
  db-store:
